### ISSUE TITLE
Fetch API cannot load 401

### ISSUE THREAD

**Issue by Geczy** [jch254/react-redux-terraform-aws#3] opened 2017-04-14 13:22 UTC
Fetch API cannot load https://62xhj71jke.execute-api.ap-southeast-2.amazonaws.com/prod/items. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://serverless-api.603.nu' is therefore not allowed access. The response had HTTP status code 401. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jch254** [comment] 2017-04-15 01:41
How did you hit that error? Using the live demo at https://serverless-api.603.nu?

**Comment by Geczy** [comment] 2017-04-17 14:16
Yes, on the /items/ page. Try adding an item and view console

**Comment by jch254** [comment] 2017-04-18 02:22
Ah, had you previously logged in (at least an hour ago)? If so I think the cause is missing Access-Control-Allow-Origin header on the 401 response from the custom authorizer. I've got an open issue for this on the API repo: https://github.com/jch254/serverless-node-dynamodb-api/issues/10. For now you could log out and log back in. I've increased the JWT expiration to 28 days.

**Comment by jch254** [comment] 2017-09-02 10:39
Fixed in https://github.com/jch254/serverless-node-dynamodb-api/commit/6615299d0c426a7fefd3b033e9ad173c90bae786

**Closed as completed by jch254** 2017-09-02 10:39 UTC
